language: ruby

rvm:
  - 2.6.4

env:
  global:
    - RAILS_ENV=test

before_install:
  - gem install bundler

before_script:
  - gem install bundle-audit

script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle-audit check --update
